name: ReneeOutofOffice
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6382393483072519
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.41020547063089907
  lightness: 0.7995778247714043
  saturation: 0.7630618496332318
  rhythmicContrast: 0.6461545072961599
purpose: []
